version: 0.2

phases:
  install:
    commands:
      # Install nvm
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      # Make nvm available in the current shell session
      - . ~/.nvm/nvm.sh
      # Install and use Node.js version 18
      - nvm install 18
      - nvm use 18
      - node -v
      # Proceed with your installation commands
      - npm install
      - cd client && npm install --legacy-peer-deps
  pre_build:
    commands:
      - echo Pre-build step
  build:
    commands:
      - echo Building the React client...
      - cd client && npm run build
artifacts:
  files:
    - '**/*'
  base-directory: client/build
  discard-paths: no
