version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - export NODE_OPTIONS=--openssl-legacy-provider


  pre_build:
    commands:
      - echo Pre-build step
      - echo "Listing the contents of the root directory:"
      - ls -al

  build:
    commands:
      - echo "Building the React client following Heroku postbuild script..."
      - cd client
      - rm -rf node_modules
      - npm install --legacy-peer-deps
      - ls -al
      - npm run build
      - cd ..

artifacts:
  files:
    - 'package.json'
    - 'server.js' # or whatever your main server file is named
    - 'Procfile'
    # Add other specific root-level files or directories required for your Node.js server
    - 'client/build/**/*' # Include the built React app
  discard-paths: no