version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing server dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Pre-build step"
      - echo "Listing the contents of the root directory:"
      - ls -al
      - echo "Checking if the client directory exists:"
      - if [ -d client ]; then echo "Client directory exists"; else echo "Client directory does not exist"; fi
  build:
    commands:
      - echo "Building the React client..."
      - cd client
      - npm install --legacy-peer-deps
      - npm run build
      - cd ..
artifacts:
  files:
    - '**/*'
  base-directory: 'client/build'
  discard-paths: no
