version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - export NODE_OPTIONS=--openssl-legacy-provider


  pre_build:
    commands:
      - echo Pre-build step
      - echo "Listing the contents of the root directory:"
      - ls -al

  build:
    commands:
      - echo "Building the React client following Heroku postbuild script..."
      - cd client
      - rm -rf node_modules
      - npm install --legacy-peer-deps
      - ls -al
      - npm run build
      - cd ..

artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*'  # Exclude all node_modules
    - '!client/node_modules/**/*'  # Exclude client's node_modules
    - '!client/src/**/*'  # Exclude source files of the client, only include the build
    - 'client/build/**/*'  # Include the built React app
  base-directory: '/
  discard-paths: no
