version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  pre_build:
    commands:
      - echo Pre-build step
      - echo "Listing the contents of the root directory:"
      - ls -al

  build:
    commands:
      - echo "Building the React client following Heroku postbuild script..."
      - cd client
      - rm -rf node_modules
      - npm install --legacy-peer-deps
      - npm run build
      - cd ..

artifacts:
  files:
    - '**/*'
  base-directory: 'client/build'
  discard-paths: no
