version: 0.2

phases:
  install:
    commands:
      - echo "Installing NVM..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      # Explicitly source the NVM script to make it available in the current session
      - . $HOME/.nvm/nvm.sh
      - echo "Installing Node.js version 18..."
      - nvm install 18
      - nvm use 18
      - node -v
      - npm -v
      # Proceed with your installation commands
      - echo "Installing project dependencies..."
      - npm install
      - cd client && npm install --legacy-peer-deps
  pre_build:
    commands:
      - echo "Pre-build step..."
  build:
    commands:
      - echo "Building the React client..."
      - cd client && npm run build
artifacts:
  files:
    - '**/*'
  base-directory: client/build
  discard-paths: no
