version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install root dependencies (if any)
      - npm install
      # Set the Node options to support legacy OpenSSL operations
      - export NODE_OPTIONS=--openssl-legacy-provider
      # Install client dependencies and build
      - cd client && npm install --legacy-peer-deps && npm run build

  pre_build:
    commands:
      - echo Pre-build step

  build:
    commands:
      - echo "Building the React client..."
      # No need to run npm run build here as we've done it in the install phase

artifacts:
  files:
    - '**/*'
  base-directory: 'client/build' # The directory to package up in the artifact
  discard-paths: no
